# fly.toml app configuration file generated for cpxy-ng on 2025-09-20T07:05:04+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cpxy-ng'
primary_region = 'hkg'

[build]
  image = 'ghcr.io/simophin/cpxy-ng:main'

[env]
  BIND_ADDR = '0.0.0.0:3000'

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
