#!/bin/sh
[ -s "${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0
. "${IPKG_INSTROOT}/lib/functions.sh"
default_postinst "$0" "$@"
if [ -z "${IPKG_INSTROOT}" ] && [ "$PKG_UPGRADE" != 1 ]; then
	cat <<MSG
cpxy-router installed. Configure it and it starts by itself:
  uci set cpxy.main.server='https://:<key>@<host>:<port>'
  uci set cpxy.main.enabled='1'
  uci commit cpxy
MSG
fi
exit 0
