[package]
name = "mobile-engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
# Builds `uniffi-bindgen`, which generates the Kotlin and Swift bindings.
bindgen = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
required-features = ["bindgen"]

[dependencies]
client = { path = "../client", features = ["dns-split"] }
cpxy-ng = { path = "../cpxy-ng" }
geoip-data = { path = "../geoip-data" }
blocklist-data = { path = "../blocklist-data" }
ipstack = "1.0.1"
etherparse = { version = "0.20", default-features = false, features = ["std"] }
tokio = { version = "1", default-features = false, features = ["macros", "net", "io-util", "rt-multi-thread", "sync", "time"] }
tracing = "0"
anyhow = "1"
futures = "0.3.31"
hickory-proto = { version = "0.25.2", default-features = false, features = ["std"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
libc = "0.2"
uniffi = "0.32.2"
thiserror = "2"

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2.2"
tracing-subscriber = "0"

[target.'cfg(target_os = "linux")'.dependencies]
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", default-features = false, features = ["signal"] }
tracing-subscriber = "0"
